version: '3'
services:
  dockerzinc:
    build: 
       context: ./docker
       dockerfile: Dockerfile
    container_name: dockerzinc
    ports:
      - "8888:8888"
    volumes:
      - "./source/:/home/jovyan/ConstraintProgramming"
    command: >
      bash -c 'chown jovyan /home/jovyan/ConstraintProgramming && 
      jupyter trust /home/jovyan/ConstraintProgramming/*.ipynb && 
      start-notebook.sh' > /dev/null